# Generated by Django 3.0 on 2022-03-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20220318_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('create_date',)},
        ),
    ]
