# Generated by Django 3.0 on 2022-03-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20220318_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'فیلم', 'verbose_name_plural': 'فیلم ها'},
        ),
    ]
