# Generated by Django 3.0 on 2022-03-25 19:27

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20220325_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_to_username),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default=1, max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
