# Generated by Django 3.0 on 2022-04-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20220325_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-create_date',), 'verbose_name': 'فیلم', 'verbose_name_plural': 'فیلم ها'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='profile',
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
