# Generated by Django 3.0 on 2022-05-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='تاریخ به اشتراک گذاری', verbose_name='تاریخ')),
                ('last_edit_date', models.DateTimeField(auto_now=True, help_text='تاریخ آخرین تغییر', verbose_name='آخرین تغییر')),
                ('content', models.CharField(max_length=500)),
                ('comment_type', models.CharField(choices=[('c', 'comment on comment'), ('v', 'comment on video')], max_length=1)),
                ('related_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_comments', to='comment.Comment')),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='به اشتراک گذارنده')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ('-create_date',),
            },
        ),
    ]
