# Generated by Django 3.0 on 2022-04-14 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20220412_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='related_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_comments', to='comment.Comment'),
        ),
    ]
