# Generated by Django 3.0 on 2022-04-14 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20220407_2230'),
        ('comment', '0003_auto_20220414_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_comments', to='video.Video'),
        ),
    ]
